### ISSUE TITLE
Woodcutter augment attempts to run server-side code on client

### ISSUE THREAD

**Issue by lexifuzzpup** [Focamacho/MysticalAdaptations#57]
When you apply the woodcutter augment to an axe and attempt to use it, it tries to run server-side code (casting to ServerPlayer without checking its environment).

Stack trace from the crash:
```
java.lang.ClassCastException: class net.minecraft.client.player.LocalPlayer cannot be cast to class net.minecraft.server.level.ServerPlayer (net.minecraft.client.player.LocalPlayer and net.minecraft.server.level.ServerPlayer are in module minecraft@1.20.1 of loader 'TRANSFORMER' @e2b3026)
	at com.focamacho.mysticaladaptations.augment.WoodcutterAugment.tryHarvest(WoodcutterAugment.java:74) ~[MysticalAdaptations-1.20.1-1.0.jar%23364!/:1.20.1-1.0] {re:classloading}
	at com.focamacho.mysticaladaptations.augment.WoodcutterAugment.harvest(WoodcutterAugment.java:54) ~[MysticalAdaptations-1.20.1-1.0.jar%23364!/:1.20.1-1.0] {re:classloading}
	at com.focamacho.mysticaladaptations.augment.WoodcutterAugment.onBlockStartBreak(WoodcutterAugment.java:36) ~[MysticalAdaptations-1.20.1-1.0.jar%23364!/:1.20.1-1.0] {re:classloading}
	at com.blakebr0.mysticalagriculture.item.tool.EssenceAxeItem.onBlockStartBreak(EssenceAxeItem.java:128) ~[MysticalAgriculture-1.20.1-7.0.3.jar%23366!/:7.0.3] {re:classloading}
```

Full crash report:
[crash-2023-09-04_21.08.17-client.txt](https://github.com/focamacho/MysticalAdaptations/files/12518158/crash-2023-09-04_21.08.17-client.txt)

**Comment by focamacho** [comment]
Fixed, thank you!!!
